import type { Student, ConceptNode } from '../types/debt';

export const DBMS_CONCEPT_NODES: ConceptNode[] = [
  {
    id: 'db-sql',
    name: 'SQL Basics',
    category: 'Relational Foundations',
    subject: 'DBMS',
    mastery: 85,
    risk: 'Low',
    prerequisites: [],
    affects: ['db-joins'],
    correctAnswers: 17,
    totalAttempts: 20,
    repeatedErrors: 1,
    lastPracticed: 'Yesterday',
    description: 'SELECT, WHERE, GROUP BY, and basic relational algebra query execution.',
    aiInsight: 'Strong grasp of foundational querying syntax.',
    position: { x: 250, y: 0 },
  },
  {
    id: 'db-joins',
    name: 'SQL Joins & Aggregates',
    category: 'Relational Foundations',
    subject: 'DBMS',
    mastery: 80,
    risk: 'Low',
    prerequisites: ['db-sql'],
    affects: ['db-fd'],
    correctAnswers: 16,
    totalAttempts: 20,
    repeatedErrors: 2,
    lastPracticed: '3 days ago',
    description: 'INNER, LEFT, RIGHT, FULL OUTER joins and Cartesian cross-product reduction.',
    aiInsight: 'Good execution on standard relational joining logic.',
    position: { x: 250, y: 120 },
  },
  {
    id: 'db-fd',
    name: 'Functional Dependency (FD)',
    category: 'Core Prerequisite Bottleneck',
    subject: 'DBMS',
    mastery: 35,
    risk: 'High',
    prerequisites: ['db-joins'],
    affects: ['db-keys', 'db-norm'],
    correctAnswers: 7,
    totalAttempts: 20,
    repeatedErrors: 8,
    lastPracticed: '2 days ago',
    description: 'Attribute closure X -> Y, Armstrong axioms, and candidate attribute determination.',
    aiInsight: 'Critical Bottleneck: Weak understanding of FD attribute closure creates cascading failure in Candidate Keys and Normalization.',
    position: { x: 250, y: 240 },
  },
  {
    id: 'db-keys',
    name: 'Candidate Keys & Superkeys',
    category: 'Intermediate Dependency',
    subject: 'DBMS',
    mastery: 40,
    risk: 'Moderate',
    prerequisites: ['db-fd'],
    affects: ['db-norm'],
    correctAnswers: 8,
    totalAttempts: 20,
    repeatedErrors: 6,
    lastPracticed: '4 days ago',
    description: 'Minimal superkey identification from functional dependency set F.',
    aiInsight: 'Requires reinforcement of FD attribute closure before determining prime vs non-prime attributes.',
    position: { x: 250, y: 360 },
  },
  {
    id: 'db-norm',
    name: 'Normalization (1NF, 2NF, 3NF, BCNF)',
    category: 'Downstream Application',
    subject: 'DBMS',
    mastery: 42,
    risk: 'High',
    prerequisites: ['db-fd', 'db-keys'],
    affects: ['db-1nf', 'db-2nf', 'db-3nf'],
    correctAnswers: 8,
    totalAttempts: 19,
    repeatedErrors: 7,
    lastPracticed: 'Yesterday',
    description: 'Decomposition of relational schemas into 1NF, 2NF, 3NF, and BCNF to eliminate insertion anomalies.',
    aiInsight: 'Illusionary high exam score (82%) masks serious 35% mastery in underlying Functional Dependency.',
    position: { x: 250, y: 480 },
  },
  {
    id: 'db-1nf',
    name: '1NF (Atomic Attributes)',
    category: 'Normal Form Level 1',
    subject: 'DBMS',
    mastery: 78,
    risk: 'Low',
    prerequisites: ['db-norm'],
    affects: [],
    correctAnswers: 15,
    totalAttempts: 19,
    repeatedErrors: 2,
    lastPracticed: '5 days ago',
    description: 'Ensuring multi-valued and composite attributes are eliminated.',
    aiInsight: 'Well understood.',
    position: { x: 100, y: 600 },
  },
  {
    id: 'db-2nf',
    name: '2NF & Partial Dependency',
    category: 'Normal Form Level 2',
    subject: 'DBMS',
    mastery: 48,
    risk: 'Moderate',
    prerequisites: ['db-norm'],
    affects: ['db-3nf'],
    correctAnswers: 9,
    totalAttempts: 19,
    repeatedErrors: 5,
    lastPracticed: 'Yesterday',
    description: 'Elimination of non-prime attribute dependencies on proper subsets of candidate keys.',
    aiInsight: 'Needs practice on prime attribute identification.',
    position: { x: 400, y: 600 },
  },
  {
    id: 'db-3nf',
    name: '3NF & Transitive Dependency',
    category: 'Normal Form Level 3',
    subject: 'DBMS',
    mastery: 38,
    risk: 'Critical',
    prerequisites: ['db-2nf'],
    affects: [],
    correctAnswers: 6,
    totalAttempts: 18,
    repeatedErrors: 7,
    lastPracticed: 'Yesterday',
    description: 'Elimination of non-prime attribute dependencies on other non-prime attributes.',
    aiInsight: 'Affected directly by weak 35% Functional Dependency foundation.',
    position: { x: 400, y: 720 },
  },
];

export const INITIAL_STUDENTS_LIST: Student[] = [
  {
    id: 'std-akash-101',
    studentId: 'STU1024',
    name: 'Akash Sharma',
    email: 'akash.sharma@learndebt.ai',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    className: 'III CSE - Sec A',
    department: 'Computer Science',
    overallGrade: 88,
    learningDebtIndex: 37,
    riskStatus: 'Moderate',
    persona: 'Exam Score Illusion (High Marks, Hidden Prerequisite Gaps)',
    summary: 'Akash scores 88% in exams by memorizing SQL queries, but has a 35% mastery in Functional Dependency.',
    learningStreakDays: 12,
    conceptsMasteredCount: 68,
    conceptsAtRiskCount: 7,
    attendanceRate: 94,
    assignmentCompletionRate: 90,
    conceptMasteries: {},
    examHistory: [
      {
        id: 'ex-1',
        title: 'Midterm Exam 1: DBMS & Relational Algebra',
        date: '2026-09-15',
        rawScore: 88,
        conceptBreakdown: [
          { conceptId: 'db-sql', conceptName: 'SQL Basics', score: 92, questionCount: 5 },
          { conceptId: 'db-joins', conceptName: 'SQL Joins', score: 85, questionCount: 5 },
          { conceptId: 'db-fd', conceptName: 'Functional Dependency', score: 35, questionCount: 5 },
        ],
      },
    ],
  },
  {
    id: 'std-arun-102',
    studentId: 'STU1025',
    name: 'Arun Kumar',
    email: 'arun.kumar@learndebt.ai',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    className: 'III CSE - Sec A',
    department: 'Computer Science',
    overallGrade: 82,
    learningDebtIndex: 72,
    riskStatus: 'Critical',
    persona: 'Prerequisite Debt Cascade',
    summary: 'Arun scored 82% in DBMS midterms, but shows a severe 72/100 Learning Debt due to unresolved Functional Dependency gaps.',
    learningStreakDays: 5,
    conceptsMasteredCount: 52,
    conceptsAtRiskCount: 12,
    attendanceRate: 91,
    assignmentCompletionRate: 88,
    conceptMasteries: {},
    examHistory: [],
  },
  {
    id: 'std-priya-103',
    studentId: 'STU1026',
    name: 'Priya S',
    email: 'priya.s@learndebt.ai',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    className: 'III CSE - Sec A',
    department: 'Computer Science',
    overallGrade: 91,
    learningDebtIndex: 48,
    riskStatus: 'Moderate',
    persona: 'Arrays Prerequisite Blindspot',
    summary: 'High overall exam score of 91%, but hidden array boundary weakness affects pointer data structures.',
    learningStreakDays: 14,
    conceptsMasteredCount: 74,
    conceptsAtRiskCount: 5,
    attendanceRate: 98,
    assignmentCompletionRate: 95,
    conceptMasteries: {},
    examHistory: [],
  },
  {
    id: 'std-rahul-104',
    studentId: 'STU1027',
    name: 'Rahul M',
    email: 'rahul.m@learndebt.ai',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    className: 'III CSE - Sec B',
    department: 'Computer Science',
    overallGrade: 76,
    learningDebtIndex: 29,
    riskStatus: 'Low',
    persona: 'Steady Practical Learner',
    summary: 'Solid foundational grasp across prerequisite concepts with low overall learning debt.',
    learningStreakDays: 9,
    conceptsMasteredCount: 61,
    conceptsAtRiskCount: 3,
    attendanceRate: 92,
    assignmentCompletionRate: 86,
    conceptMasteries: {},
    examHistory: [],
  },
  {
    id: 'std-sneha-105',
    studentId: 'STU1028',
    name: 'Sneha R',
    email: 'sneha.r@learndebt.ai',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    className: 'III CSE - Sec B',
    department: 'Computer Science',
    overallGrade: 86,
    learningDebtIndex: 54,
    riskStatus: 'High',
    persona: 'Trigonometry Prerequisite Debt',
    summary: 'Strong algebraic logic, but calculus integration shows severe prerequisite identity debt.',
    learningStreakDays: 8,
    conceptsMasteredCount: 65,
    conceptsAtRiskCount: 8,
    attendanceRate: 89,
    assignmentCompletionRate: 91,
    conceptMasteries: {},
    examHistory: [],
  },
];

export const studentService = {
  getStudentById: (id: string): Student => {
    return INITIAL_STUDENTS_LIST.find((s) => s.id === id || s.studentId === id) || INITIAL_STUDENTS_LIST[0];
  },
  getAllStudents: (): Student[] => {
    return INITIAL_STUDENTS_LIST;
  },
  getDBMSConceptNodes: (): ConceptNode[] => {
    return DBMS_CONCEPT_NODES;
  },
};
